### PR TITLE
Hls segments

### LINKED ISSUE #797: HLS master EXT-X-INDEPENDENT-SEGMENTS thinks we always have audio and video in separate files.
in the playlist for https://se.eurosportplayer.com/event/sport-/12fca6fb-af39-45ef-abb2-1a719b5d428e

we can see 

```
#EXTM3U
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-STREAM-INF:RESOLUTION=896x504,AVERAGE-BANDWIDTH=1900000,BANDWIDTH=2200000,CODECS="avc1.4d001f,mp4a.40.2",CLOSED-CAPTIONS=NONE
1800K/1800_complete.m3u8
#EXT-X-STREAM-INF:RESOLUTION=320x180,AVERAGE-BANDWIDTH=188000,BANDWIDTH=202000,CODECS="avc1.42001e,mp4a.40.2",CLOSED-CAPTIONS=NONE
192K/192_complete.m3u8
#EXT-X-STREAM-INF:RESOLUTION=384x216,AVERAGE-BANDWIDTH=514000,BANDWIDTH=565000,CODECS="avc1.42001e,mp4a.40.2",CLOSED-CAPTIONS=NONE
450K/450_complete.m3u8
#EXT-X-I-FRAME-STREAM-INF:RESOLUTION=384x216,BANDWIDTH=125000,CODECS="avc1.42001e",URI="450K/450_complete_iframe.m3u8"
#EXT-X-STREAM-INF:RESOLUTION=512x288,AVERAGE-BANDWIDTH=895000,BANDWIDTH=1000000,CODECS="avc1.42001e,mp4a.40.2",CLOSED-CAPTIONS=NONE
800K/800_complete.m3u8
#EXT-X-STREAM-INF:RESOLUTION=640x360,AVERAGE-BANDWIDTH=1300000,BANDWIDTH=1450000,CODECS="avc1.4d001f,mp4a.40.2",CLOSED-CAPTIONS=NONE
1200K/1200_complete.m3u8
#EXT-X-STREAM-INF:RESOLUTION=960x540,AVERAGE-BANDWIDTH=2600000,BANDWIDTH=3000000,CODECS="avc1.4d001f,mp4a.40.2",CLOSED-CAPTIONS=NONE
2500K/2500_complete.m3u8
#EXT-X-I-FRAME-STREAM-INF:RESOLUTION=960x540,BANDWIDTH=950000,CODECS="avc1.4d001f",URI="2500K/2500_complete_iframe.m3u8"
#EXT-X-STREAM-INF:RESOLUTION=1280x720,AVERAGE-BANDWIDTH=3600000,BANDWIDTH=4250000,CODECS="avc1.640028,mp4a.40.2",CLOSED-CAPTIONS=NONE
3500K/3500_complete.m3u8
````

for some reason it thinks that  3500K/3500_complete.m3u8 have audio and video in seperate files but its not. its in the **same file**.

because of that, we are getting this when the download is finished 
```
INFO [1518394530.881428] /Users/johan/dev/svtplay-dl-dev/lib/svtplay_dl/postprocess/__init__.py/merge: Merge audio and video into sport.eurosport.player.mp4
ERROR [1518394530.961024] /Users/johan/dev/svtplay-dl-dev/lib/svtplay_dl/postprocess/__init__.py/merge: Something went wrong: sport.eurosport.player.m4a: No such file or directory
```

When we see `EXT-X-INDEPENDENT-SEGMENTS` we set `self.segments` to `True` 
because of that we try to merge the files together thanks to 
`if stream.name() == "dash" or (stream.name() == "hls" and stream.options.segments) and post.detect:` in `get_one_media`

Maybe we should check if we have an audio track before trying to do a post.merge?
Maybe we should override it earlier in `hls.download()`?  here is `self.audio` `None`
Maybe `EXT-X-INDEPENDENT-SEGMENTS` thing is wrong?

### PR DESCRIPTION
**Pull request by dalgr**
Fixes #797

### CODE REVIEW

**Comment by dalgr** [comment]
@spaam 
What do you think? Can you test it for eurosport.

**Comment by spaam** [comment]
@dalgr im testing it on eurosport now :)

**Comment by dalgr** [comment]
It works with svt1 live, tv4 live and dpaly:(`https://dplaynordics-vod-88.akamaized.net/dplaydni/19277/0/hls/321629001/playlist.m3u8?hdnts=st=1518467541~exp=1518553941~acl=/*~hmac=0e193f4fd4f1bec0ee387ff70b2800c9580b5b9d736e3dfc286a929edb05ab21`)

**Comment by spaam** [comment]
it works great with eurosport, so LGTM

**Pull request merged**
