### PR TITLE
Improve m3u parser

### PR DESCRIPTION
**Pull request by dalgr**
A work i progress of a improved  m3u parser, I am planing on adding more value error checks( like L258, and maybe compress it a bit).

I have tested with links from svt, tv4 and vidme(And all work).
``` json
https://www.svtplay.se/video/7677452/fallet-oj-simpson-american-crime-story/fallet-o-j-simpson-american-crime-story-sasong-1-the-race-card
http://www.tv4.se/s%C3%A5-mycket-b%C3%A4ttre/klipp/kikki-danielsson-at-the-border-3940110
https://vid.me/S49Ge
```
Still need to test with something that is  encrypted, to check that it works.

### CODE REVIEW

**Comment by spaam** [comment]
ohh nice. i pushed some stuff so this `https://www.rmp-streaming.com/media/rmp-segment/bbb-abr-aes/playlist.m3u8` will work.  `python -m svtplay_dl https://www.rmp-streaming.com/media/rmp-segment/bbb-abr-aes/playlist.m3u8` if you want to test encrypted.

**Comment by dalgr** [comment]
I got it working in my new commit :)

**Comment by spaam** [comment]
do you know if there is a way to detect if the audio and video is separate files?

**Comment by dalgr** [comment]
Yes, for example is noticed that it is only possible to download video for `https://vid.me/S49Ge`(i overlooked it before). This due to it's m3u8 syntax.
``` m3u8
#EXTM3U
#EXT-X-VERSION:6

# Media Playlists

# Audio
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio/mp4a",LANGUAGE="und",NAME="Unknown",AUTOSELECT=YES,DEFAULT=YES,URI="https://api.vid.me/video/18060744/stream?format=hls&subformat=62944803-audio-und-mp4a-1.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio/mp4a",LANGUAGE="und",NAME="Unknown",AUTOSELECT=YES,DEFAULT=YES,URI="https://api.vid.me/video/18060744/stream?format=hls&subformat=62944803-audio-und-mp4a-2.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio/mp4a",LANGUAGE="und",NAME="Unknown",AUTOSELECT=YES,DEFAULT=YES,URI="https://api.vid.me/video/18060744/stream?format=hls&subformat=62944803-audio-und-mp4a-3.m3u8"

# Video
#EXT-X-STREAM-INF:AUDIO="audio/mp4a",AVERAGE-BANDWIDTH=2102174,BANDWIDTH=2780072,CODECS="avc1.42C01F,mp4a.40.2",RESOLUTION=854x480
https://api.vid.me/video/18060744/stream?format=hls&subformat=62944803-video-avc1-1.m3u8
#EXT-X-STREAM-INF:AUDIO="audio/mp4a",AVERAGE-BANDWIDTH=547478,BANDWIDTH=1012639,CODECS="avc1.42C015,mp4a.40.2",RESOLUTION=426x240
https://api.vid.me/video/18060744/stream?format=hls&subformat=62944803-video-avc1-2.m3u8
#EXT-X-STREAM-INF:AUDIO="audio/mp4a",AVERAGE-BANDWIDTH=2127736,BANDWIDTH=4344117,CODECS="avc1.64001F,mp4a.40.2",RESOLUTION=1280x720
https://api.vid.me/video/18060744/stream?format=hls&subformat=62944803-video-avc1-3.m3u8
#EXT-X-STREAM-INF:AUDIO="audio/mp4a",AVERAGE-BANDWIDTH=2990618,BANDWIDTH=5997490,CODECS="avc1.640028,mp4a.40.2",RESOLUTION=1920x1080
https://api.vid.me/video/18060744/stream?format=hls&subformat=62944803-video-avc1-4.m3u8
```
You can see that under "EXT-X-MEDIA" tag the attribute name "GROUP-ID" is given an attribute value of "audio/mp4a" (`GROUP-ID="audio/mp4a"`).

This is late referenced form "EXT-X-STREAM-INF" tag, attribute name "AUDIO" with the same value "audio/mp4a" (`AUDIO="audio/mp4a"`).

p.s
Also from "https://tools.ietf.org/html/rfc8216#section-4.3.4.1":
EXT-X-MEDIA:
```
GROUP-ID

      The value is a quoted-string that specifies the group to which the
      Rendition belongs.  See Section 4.3.4.1.1.  This attribute is
      REQUIRED.
```

EXT-X-STREAM-INF:
```
AUDIO

      The value is a quoted-string.  It MUST match the value of the
      GROUP-ID attribute of an EXT-X-MEDIA tag elsewhere in the Master
      Playlist whose TYPE attribute is AUDIO.  It indicates the set of
      audio Renditions that SHOULD be used when playing the
      presentation.  See Section 4.3.4.2.1.

      The AUDIO attribute is OPTIONAL.
```

**Comment by spaam** [comment]
@dalgr , do you think we can merge this to master or is there anything more to be fixed?

**Comment by dalgr** [comment]
@spaam I have some local changes that I need to lookover first. Will try to finish it tomorrow

**Comment by spaam** [comment]
@dalgr no hurry, merge this for the release after 1.9.7. thanks for working on this :)

**Comment by dalgr** [comment]
@spaam I have pushed my local changes now

**Comment by spaam** [comment]
@dalgr , thank you so much fixing this <3

**Pull request merged**
