### PR TITLE
Add any unix install instructions

### PR DESCRIPTION
**Pull request by Jacalz**
I noticed that the install.md file on svtplay-dl-web had the instructions for how to install on any Unix system and I thought that they could be a great addition to the new README file here :+1: 
Also noticed that install.md only had 3 ``` instead of 4 so I removed the forth one and removed some spaces I found laying around.

### CODE REVIEW

**Comment by Jacalz** [comment]
Going to rebase the commits when I get home 🙂

**Comment by Jacalz** [comment]
The commits have been squashed so this is now ready to be merged as long as you accept the changes 🙂

**Comment by Jacalz** [comment]
Any news on merging this? :sweat_smile: @spaam

**Comment by spaam** [comment]
@Jacalz later today. right now the command is gone so need to fix that before adding this :)

**Comment by spaam** [comment]
bit late with this but anyway .. thanks for the pull request <3

**Comment by Jacalz** [comment]
Don’t worry, take your time 👍

**Pull request merged**
