### PR TITLE
Add support of downloading a 'media_segment' m3u8 file

### LINKED ISSUE #654: M3U8 Download function
Hi it is possible to add one
Unencrypted M3U8(hls) Download function
Master / direct
So you can download things outside of the added streams
If you have the M3U8 link of course :)

If that feature already exists then sorry
I just could not find it :)

-------------------------------------------------- -----
I would also like to thank you for the super cool tool you have made here
It's all too nice

### PR DESCRIPTION
**Pull request by dalgr**
fixes #654

### CODE REVIEW

**Comment by spaam** [comment]
nice :)

@dalgr  , do you want to have commit access to the repo? :)

**Comment by spaam** [comment]
@dalgr , do you want to have commit access to the repo? :)

**Comment by dalgr** [comment]
@spaam 
Thanks, would be really nice :)

**Comment by spaam** [comment]
@dalgr done :)

**Pull request merged**
