### PR TITLE
just initial pr to help devs to find the way for .es support

### PR DESCRIPTION
**Pull request by felisucoibi**
this is a not working pr

### CODE REVIEW

**Comment by felisucoibi** [comment]
as

**Comment by spaam** [comment]
you should fix those errors.

Does this work with -A to get all episodes for a tv-series?

**Comment by felisucoibi** [comment]
> you should fix those errors.
> 
> Does this work with -A to get all episodes for a tv-series?

no its not working at all, i don't know if i miss something else to fix, or I need something else to modify....

If I use :
svtplay-dl -u myuser -p mypass https://www.dplay.es/series/091-alerta-policia
ERROR: No videos found. Need the 'st' cookie to work

If I use the -A without cokkie or login:

svtplay-dl -A https://www.dplay.es/series/091-alerta-policia
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/svtplay-dl/__main__.py", line 15, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 66, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 59, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 77, in get_all_episodes
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/dplay.py", line 137, in find_all_episodes
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/dplay.py", line 186, in _login
KeyError: 'data'

If I use with a cookie file:

svtplay-dl -A --cookie dplay.txt https://www.dplay.es/series/091-alerta-policia
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/svtplay-dl/__main__.py", line 15, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 66, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 47, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/__init__.py", line 217, in service_handler
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/__init__.py", line 42, in __init__
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py", line 29, in __init__
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py", line 45, in split_header
ValueError: dictionary update sequence element #0 has length 1; 2 is required

**Comment by felisucoibi** [comment]
Here I added all the info for .es support, all the language differences in URL's
https://github.com/spaam/svtplay-dl/issues/1285

**Comment by felisucoibi** [comment]
ASDA

**Pull request closed without merging**
