### PR TITLE
Add support for live svtplay using hls

### PR DESCRIPTION
**Pull request by dalgr**
Related to #47

### CODE REVIEW

**Comment by dalgr** [comment]
Tested with:
```
./svtplay-dl https://www.svtplay.se/kanaler/svt1 --stream-priority=hls
./svtplay-dl https://www.svtplay.se/kanaler/svt2 --stream-priority=hls
./svtplay-dl https://www.svtplay.se/kanaler/svt24 --stream-priority=hls
```

**Comment by spaam** [comment]
you run this until you press ctrl+c  ?

**Comment by dalgr** [comment]
yes

**Comment by spaam** [comment]
nice. i was going to look at using threads but i guess its not needed.

**Comment by dalgr** [comment]
Thanks, I think it is still possible reduce the download time with multithreading

**Comment by dentarg** [comment]
Cool! 👍 

What happened to `-c` mentioned in https://github.com/spaam/svtplay-dl/issues/47#issuecomment-307853478 to specify capture time? Sounded neat.

**Comment by dalgr** [comment]
@dentarg
Thanks, I have now added `-c` (`capture_time`)

**Comment by spaam** [comment]
@dalgr the capture_time is breaking the ctrl+c option

**Comment by spaam** [comment]
saw that when im fixing this live thing for dplay :)

**Comment by omidontop** [comment]
👍

**Comment by dalgr** [comment]
@omidontop
Thanks :)

**Pull request merged**
