### PR TITLE
Add service Barnkanalen

### PR DESCRIPTION
**Pull request by frals**
Heavily based on svtplay

### CODE REVIEW

**Comment by spaam** [comment]
many of this seems pretty similar to svtplay. try replacing `Service, OpenGraphThumbMixin` with svtplay, remove functions seasoninfo, outputfilename, videos_to_list, _genre, and _get_video. after that see if it still works.

**Comment by frals** [comment]
videos_to_list uses a different key compared with svtplay and since it pretty minor i figured it could stay in barnkanalen. figured the minor tweaks to svtplay was worth it to avoid duplicating the rest of the functions

**Comment by Sopor-** [comment]
All programs you find on Barnkanalen.se you will find on svtplay.se

**Comment by spaam** [comment]
@Sopor- , yes, but some people want to be able to download it from Barnkanalen.se :)

**Pull request merged**
