### PR TITLE
urplay sd-only program fixed

### LINKED ISSUE #1296: urplay.se crashes on Mytologerna (possibly because no HD stream)
### svtplay-dl versions:

Run `svtplay-dl --version`

### Operating system and Python version:

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal

Python 3.8.5

### What is the issue:

urplay crashes on urplay. It seems to crash if there is no HD version of the program (I'm pretty sure the show "Mytologernna" is only SD). Dowloading other more recent shows works fine.

normal@home:~$ svtplay-dl -v https://urplay.se/program/166843-mytologerna-tomten
DEBUG [1609245406.002606] /usr/lib/python3/dist-packages/svtplay_dl/utils/getmedia.py/get_media: version: 2.8
DEBUG [1609245406.003669] /usr/lib/python3/dist-packages/svtplay_dl/service/__init__.py/__init__: service: urplay
DEBUG [1609245406.003737] /usr/lib/python3/dist-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://urplay.se/program/166843-mytologerna-tomten'
DEBUG [1609245406.0050793] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): urplay.se:443
DEBUG [1609245406.0328333] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://urplay.se:443 "GET /program/166843-mytologerna-tomten HTTP/1.1" 200 70282
DEBUG [1609245406.0478506] /usr/lib/python3/dist-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://streaming-loadbalancer.ur.se/loadbalancer.json'
DEBUG [1609245406.048852] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): streaming-loadbalancer.ur.se:443
DEBUG [1609245406.073669] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://streaming-loadbalancer.ur.se:443 "GET /loadbalancer.json HTTP/1.1" 200 None
DEBUG [1609245406.075326] /usr/lib/python3/dist-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://streaming10.ur.se/urplay/_definst_/mp4:166000-166999/166843-21.mp4/playlist.m3u8'
DEBUG [1609245406.0766556] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): streaming10.ur.se:443
DEBUG [1609245406.1015148] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://streaming10.ur.se:443 "GET /urplay/_definst_/mp4:166000-166999/166843-21.mp4/playlist.m3u8 HTTP/1.1" 200 None
Traceback (most recent call last):
  File "/usr/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/lib/python3/dist-packages/svtplay_dl/__init__.py", line 66, in main
    get_media(urls[0], config, __version__)
  File "/usr/lib/python3/dist-packages/svtplay_dl/utils/getmedia.py", line 61, in get_media
    get_one_media(stream)
  File "/usr/lib/python3/dist-packages/svtplay_dl/utils/getmedia.py", line 111, in get_one_media
    for i in streams:
  File "/usr/lib/python3/dist-packages/svtplay_dl/service/urplay.py", line 38, in get
    url = "https://{}/{}playlist.m3u8".format(loadbalancer, stream["hd"]["location"])
KeyError: 'hd'

### PR DESCRIPTION
**Pull request by awabom**
Fixes #1296 - download of programs without hd streams on urplay.se

### CODE REVIEW

**Comment by awabom** [comment]
Btw - first time ever coding in Python...

**Comment by awabom** [comment]
Maybe could use a loop over "sd" and "hd" since the code in the original version is duplicated (as is mine)

**Comment by spaam** [comment]
looks good. but can you fix the commit message?  `Add files via upload` does not really say what is fixed and the script does not really upload anything .)

**Comment by awabom** [comment]
> 
> 
> looks good. but can you fix the commit message? `Add files via upload` does not really say what is fixed and the script does not really upload anything .)

Ah, accidentally commited github's standard web-ui commit message. Looks like my commit --amend + push --force fixed it?

**Comment by spaam** [comment]
yeah that will fix it :)

**Comment by spaam** [comment]
great,  thank you for the pr  ❤️

**Pull request merged**
